- name: Install Nginx
  hosts: WEB
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Make sure a service unit is running
      ansible.builtin.systemd_service:
        state: started
        name: httpd
        enabled: true